apiVersion: v1
kind: Service
metadata:
  name: chatapp-backend1-lb
spec:
  type: LoadBalancer
  ports:
  - name: "chatapp-rest"
    port: 8000
    protocol: TCP
    targetPort: 3000
  - name: "chatapp-socket"
    port: 8080
    protocol: TCP
    targetPort: 3001
  selector:
    app: chatapp-backend1
