BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id  BIGSERIAL  PRIMARY KEY ,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;

COMMIT;